### ISSUE TITLE
Timeout does not work - Race conditions and panics

### ISSUE THREAD

**Issue by ajbeach2** [ajbeach2/sqsworker#21]
The following test fails via panic:
```
func TestTimerSetup(t *testing.T) {
	queue := GetMockeQueue()
	done := make(chan bool)

	var handlerFunction = func(ctx context.Context, m *sqs.Message) ([]byte, error) {
		transform := fmt.Sprint(*m.Body, " ", "world")
		return []byte(transform), nil
	}

	var callback = func(result []byte, err error) {
		if string(result) != "hello world" {
			t.Error("Expected: ", "hello world", "Actual: ", string(result))
		}
		close(done)
	}

	sess := session.New(&aws.Config{Region: aws.String("us-east-1")})
	w := sqsworker.NewWorker(sess, sqsworker.WorkerConfig{
		QueueIn:  "https://sqs.us-east-1.amazonaws.com/88888888888/In",
		QueueOut: "https://sqs.us-east-1.amazonaws.com/88888888888/Out",
		Workers:  1,
		Logger:   zap.NewNop(),
		Handler:  handlerFunction,
		Callback: callback,
		Timeout:  1,
		Name:     "TestApp",
	})
	w.Queue = queue

	go func() {
		time.Sleep(2 * time.Second)
		queue.Push("hello")
		queue.Pop()
		<-done
		w.Close()
	}()

	w.Run()
	queue.Close()
	return
}
```

```
go test -v -coverprofile=cover.out -timeout 30s
=== RUN   TestTimeout
=== PAUSE TestTimeout
=== RUN   TestError
--- PASS: TestError (0.00s)
=== RUN   TestProcessMessage
--- PASS: TestProcessMessage (0.00s)
=== RUN   TestTimerSetup
coverage: 92.1% of statements
panic: test timed out after 30s

goroutine 49 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/Cellar/go/1.11.4/libexec/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001ae500, 0x141d01f, 0xe, 0x14326c0, 0x1078501)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc0001ae000)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc0001ae000, 0xc000135da0)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf
testing.runTests(0xc0000aecc0, 0x1728da0, 0x4, 0x4, 0x100d46f)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc00011e080, 0x0)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:102 +0x205

goroutine 36 [chan receive]:
testing.(*T).Parallel(0xc0001ae100)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:732 +0x1fa
github.com/ajbeach2/sqsworker_test.TestTimeout(0xc0001ae100)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker_test.go:100 +0x43
testing.tRunner(0xc0001ae100, 0x14326a8)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:878 +0x35c

goroutine 43 [semacquire]:
sync.runtime_Semacquire(0xc00009cb38)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00009cb30)
	/usr/local/Cellar/go/1.11.4/libexec/src/sync/waitgroup.go:130 +0x64
github.com/ajbeach2/sqsworker.(*Worker).Run(0xc00011ed00)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:243 +0x31c
github.com/ajbeach2/sqsworker_test.TestTimerSetup(0xc0001ae500)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker_test.go:256 +0x3c4
testing.tRunner(0xc0001ae500, 0x14326c0)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:878 +0x35c

goroutine 47 [select]:
github.com/ajbeach2/sqsworker.(*Worker).consumer(0xc00011ed00, 0x14bc700, 0xc00009eec0, 0xc0000aaa20)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:155 +0x19d
github.com/ajbeach2/sqsworker.(*Worker).Run.func3(0xc00009cb30, 0xc00011ed00, 0x14bc700, 0xc00009eec0, 0xc0000aaa20)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:240 +0x7d
created by github.com/ajbeach2/sqsworker.(*Worker).Run
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:238 +0x2e6

goroutine 46 [chan receive]:
github.com/ajbeach2/sqsworker.(*Worker).Run.func2(0xc00011ed00, 0xc000093520)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:229 +0x42
created by github.com/ajbeach2/sqsworker.(*Worker).Run
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:228 +0x17f

goroutine 45 [chan receive]:
github.com/ajbeach2/sqsworker_test.(*MockQueue).ReceiveMessageRequest(0xc00009ee40, 0xc0000aaae0, 0x0, 0xc0000aeec0)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker_test.go:32 +0x45
github.com/ajbeach2/sqsworker.(*Worker).producer(0xc00011ed00, 0x14bc700, 0xc00009eec0, 0xc0000aaa20)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:196 +0x1d6
github.com/ajbeach2/sqsworker.(*Worker).Run.func1(0xc00011ed00, 0x14bc700, 0xc00009eec0, 0xc0000aaa20)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:224 +0x53
created by github.com/ajbeach2/sqsworker.(*Worker).Run
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:223 +0x146

goroutine 44 [chan receive]:
github.com/ajbeach2/sqsworker_test.(*MockQueue).Pop(...)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker_test.go:49
github.com/ajbeach2/sqsworker_test.TestTimerSetup.func3(0xc00009ee40, 0xc000082780, 0xc00011ed00)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker_test.go:251 +0x83
created by github.com/ajbeach2/sqsworker_test.TestTimerSetup
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker_test.go:248 +0x3b6

goroutine 48 [chan send]:
github.com/ajbeach2/sqsworker.(*Worker).exec.func1(0xc00011ed00, 0x14bc700, 0xc00009eec0, 0xc00009ee80, 0xc0000af080)
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:132 +0xb6
created by github.com/ajbeach2/sqsworker.(*Worker).exec
	/Users/alexanderbeach/go/src/github.com/ajbeach2/sqsworker/sqsworker.go:128 +0xb8
exit status 2
FAIL	github.com/ajbeach2/sqsworker	30.023s
```

There are a few issues with the timeout code:
1. Race conditions with the timer itself
2. The  hp.Done channel may block indefinitely, if there was a previous timeout and the done channel read never happened

```
func (w *Worker) exec(ctx context.Context, hp *handlerParams, m *sqs.Message) ([]byte, error) {
	hp.Timer.Reset(w.Timeout)

	go func() {
		result, err := w.Handler(ctx, m)
		hp.Result.Result = result
		hp.Result.Err = err
		hp.Done <- hp.Result
	}()

	select {
	case result := <-hp.Done:
		if !hp.Timer.Stop() {
			<-hp.Timer.C
		}
		return result.Result, result.Err
	case <-hp.Timer.C:
		return nil, &HandlerTimeoutError{}
	}
}
````

Not sure the fix, this will need to be refactored or removed until timer logic can be fixed.

**Comment by ajbeach2** [comment]
Closing in favor of removing the timer all together until a better solution can be implemented.
